refresh_rate: 60 #In seconds
notification_url: http://api.telegram.org/bot*****/sendMessage?chat_id=182195759&text={TEXT} #Use {TEXT} to reference where to paste messages
zipline_path: /Users/lesterrry/Downloads/campfire-master/zipline.scpt #Path to zipline.scpt file